"""initial schema

Revision ID: 61901b4899b2
Revises: 
Create Date: 2026-05-20 14:36:07.405308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61901b4899b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('course', sa.String(), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_fixed', sa.Boolean(), nullable=True),
    sa.Column('fixed_start', sa.DateTime(), nullable=True),
    sa.Column('fixed_end', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('available_days', sa.String(), nullable=True),
    sa.Column('day_start', sa.String(), nullable=True),
    sa.Column('day_end', sa.String(), nullable=True),
    sa.Column('max_sessions_per_day', sa.Integer(), nullable=True),
    sa.Column('min_break_minutes', sa.Integer(), nullable=True),
    sa.Column('preferred_session_mins', sa.Integer(), nullable=True),
    sa.Column('max_session_mins', sa.Integer(), nullable=True),
    sa.Column('schedule_dirty', sa.Boolean(), nullable=True),
    sa.Column('blocked_dates', sa.String(), nullable=True),
    sa.Column('last_schedule_explanation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('scheduled_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_sessions')
    op.drop_table('user_preferences')
    op.drop_table('tasks')
    # ### end Alembic commands ###
