"""add user_id to user_preferences

Revision ID: db61259f27d7
Revises: ed30926963a7
Create Date: 2026-06-04 09:25:42.408399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db61259f27d7'
down_revision: Union[str, Sequence[str], None] = 'ed30926963a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('user_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'user_preferences', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_preferences', type_='unique')
    op.drop_column('user_preferences', 'user_id')
    # ### end Alembic commands ###
