"""add advanced fields and chat tables

Revision ID: e44599315406
Revises: 40c659f656c7
Create Date: 2026-06-04 08:45:31.658223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44599315406'
down_revision: Union[str, Sequence[str], None] = '40c659f656c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('tool_calls', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('memory_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_referenced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasks', sa.Column('source', sa.String(), nullable=False, server_default='manual'))
    op.add_column('tasks', sa.Column('is_fixed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('tasks', sa.Column('fixed_start', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('fixed_end', sa.DateTime(), nullable=True))
    op.add_column('user_preferences', sa.Column('blocked_dates', sa.String(), nullable=False, server_default=''))
    op.add_column('user_preferences', sa.Column('last_schedule_explanation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'last_schedule_explanation')
    op.drop_column('user_preferences', 'blocked_dates')
    op.drop_column('tasks', 'fixed_end')
    op.drop_column('tasks', 'fixed_start')
    op.drop_column('tasks', 'is_fixed')
    op.drop_column('tasks', 'source')
    op.drop_table('user_memories')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
